#!/bin/bash
#cd $(dirname "$0");
file=$3;
f=$1;
t=$2;

fileType=`file ${file}`;
grepResult=`echo ${fileType}|grep -i ${t}`;
#echo "echo ${fileType}|grep ${f}"
#echo ${grepResult};
if [ "${grepResult}" != '' ]; then
	echo "[${file}]: error :  iconv ignore "
	#exit;
fi
touch .iconvTempFile
iconv -f ${f} -t ${t} ${file} >.iconvTempFile ;
#echo "iconv -f ${f} -t ${t} ${file} >a;"
if [ $? == "1" ]; then
	echo "[${file}] error: iconv error"
else
	cat .iconvTempFile > ${file};
	echo "[${file}] iconv finish";
fi
rm .iconvTempFile;
